version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: AssessmentDB
    ports:
      - "9300:9300"  # Expose PostgreSQL at port 5432 on localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

  airflow:
    image: quay.io/astronomer/astro-runtime:11.1.0
    environment:
#      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:admin@postgres:9300/AssessmentDB
      AIRFLOW_HOME: /usr/local/airflow
    depends_on:
      - postgres
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
    ports:
      - "9900:9900"  # Expose Airflow webserver at port 8080 on localhost
    command:
      - airflow db init
      - airflow users  create --role Admin --username admin --email admin --firstname admin --lastname admin --password admin
    entrypoint: ["airflow", "webserver", "--port", "9900"]
       # Start the webserver

volumes:
  postgres_data: